### PR TITLE
Copy bug report btn

### LINKED ISSUE #4097: Request: システム情報をコピーできると便利
バグ報告のテンプレートにシステム情報を書く部分があります。
https://{GROWI_HOST}/admin にアクセスするとその情報が見れるようになっていると思いますが、テンプレートの表の並びとシステム情報の表示の並びが異なっているため確認しながら手入力が必要です。
また、システム情報画面をコピー＆ペーストするとHTMLタグが含まれる形でコピーされてしまいます。

バグ報告に記載するべき情報をまとめてクリップボードにコピーするボタンがあると便利かと思いますので、提案させて頂きます。

### PR DESCRIPTION
**Pull request by Mxchaeltrxn**
@yuki-takei This PR closes #4097

The first thing you might notice is that I've done more than just make a button. This is because I did not feel that there was a good spot for the button on the page as it doesn't make sense anywhere on the page, so I created a section and gave it some context.

## Changes made
- Add section on `AdminHome` for submitting bug reports.
- Add button to `AdminHome` that allows the user to copy the bug report markdown with prefilled system information values.
- Make the button text change when clicked and then return to default after a delay.
- Add link to GitHub for submitting a bug report.
- I've also made a typo fix in my second commit that is completely unrelated to the current fix. I can make this in a new PR instead if you'd like.

## Notes
- If my work so far is approved, translations for the above changes will need to be made for Japanese and Chinese.
- I searched online and it is possible to get the client's OS and browser information but I think it is not easy to do and will require future maintenance as browsers update so it's not worthwhile. All I've retrieved was the user's system information, which is already available.

#### Light mode:
image
#### Light mode (button clicked, bug report is now in my clipboard). Note the button text:
image
#### Dark mode: 
image
#### Bug report with prefilled system information:
image

### CODE REVIEW

File: packages/app/src/client/services/AdminHomeContainer.js [hunk 1]
```diff
@@ -44,19 +55,113 @@ export default class AdminHomeContainer extends Container {
...
+|GROWI     |${this.state.growiVersion}|
+|node.js   |${this.state.nodeVersion}|
+|npm       |${this.state.npmVersion}|
+|yarn      |${this.state.yarnVersion}|
+|Using Docker|yes/no|
+|Using [growi-docker-compose][growi-docker-compose]|yes/no|
+
+[growi-docker-compose]: https://github.com/weseek/growi-docker-compose
+
+*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*
```
Comment (yuki-takei) [inline packages/app/src/client/services/AdminHomeContainer.js:112]: I think the text that will be copied by CopyToClipboard should be enough only these lines I marked.

**Review by yuki-takei — CHANGES_REQUESTED** [review]

File: packages/app/src/client/services/AdminHomeContainer.js (hunk 1 above)
Comment (Mxchaeltrxn) [reply packages/app/src/client/services/AdminHomeContainer.js]: I've made the changes you requested. @yuki-takei

Screenshot:
image


My clipboard now holds:
```md
| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.3.3-RC|
|node.js   |14.17.4|
|npm       |6.14.14|
|yarn      |1.22.5|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*
```

## Note
Translations still need to be done.
